@startuml
skinparam handwritten true
start
if (multiprocessor?) then (yes)
  fork
    :Treatment 1;
  fork again
    :Treatment 2a;
    :Treatment 2b;
  end fork
else (monoproc)
  :Treatment 1;
  :Treatment 2;
  :Treatment 3;  
endif
@enduml
